# Generated by Django 4.2.5 on 2023-09-25 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=100)),
                ('work', models.CharField(blank=True, max_length=100)),
                ('education', models.CharField(blank=True, max_length=100)),
                ('hobbies', models.TextField(blank=True)),
                ('password', models.CharField(max_length=50, null=True)),
                ('link', models.URLField(blank=True)),
                ('profile_image', models.FileField(blank=True, upload_to='profile/')),
                ('relationship', models.CharField(blank=True, choices=[('Singel', 'Singel'), ('Married', 'Married'), ('Try to SHADi', 'Try to SHADi')], max_length=15)),
                ('followers', models.PositiveIntegerField(default=0)),
                ('contact', models.CharField(max_length=12, null=True)),
                ('following', models.PositiveIntegerField(default=0)),
                ('follows', models.ManyToManyField(blank=True, related_name='followed_by', to='media_app.profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post_image', models.FileField(null=True, upload_to='post/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_app.profile')),
            ],
            options={
                'db_table': 'Post',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('liked_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='media_app.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_app.profile')),
            ],
            options={
                'db_table': 'Like',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_app.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_app.profile')),
            ],
            options={
                'db_table': 'Comment',
            },
        ),
    ]
